spring:
  application:
    name: northwind
  datasource:
    url: jdbc:postgresql://localhost:5432/Northwind
    username: postgres
    password: aeb14eb11
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true  
    javax:
      persistence:
        validation:
          mode: none
  main:
    banner-mode: off

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true  

server:
  port: 8080
